### ISSUE TITLE
Rename the scratch descriptor

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/image-spec#1067]
The scratch descriptor is being confused with the scratch pseudo-image used by Docker and others to indicate an empty image. Examples of this confusion include:

- The WASM Artifacts implementation: <https://docs.google.com/document/d/11shgC3l6gplBjWF1VJCWvN_9do51otscAm0hBDGSSAc/edit>
- Confusion from other spec maintainers: <https://github.com/moby/moby/pull/45592#discussion_r1201801043>

At the risk of creating another "artifact manifest" chaos, I think we should consider renaming the "scratch descriptor" and the associated media type to something that won't be confused with "FROM scratch" before we GA this and are stuck with the confusion. Instead of scratch, perhaps nil, empty, or blank?

**Comment by tianon** [comment]
I worry whether folks have already started to use the new media type, but perhaps they haven't and this is indeed reasonable for us to change now?  Not sure how we get the question out effectively enough to survey the downstream impact. :grimacing:

More naming ideas: "placeholder", "spec-filler", "empty-config", "plain"

(of the proposals so far, my own preference is for "nil" because it makes it feel semantically more wrong to have something like `"layers": ["nil", "not-nil", "not-nil"]`)

**Comment by sudo-bmitch** [comment]
The end user impact of this should be a change to the media type. And the old media type never made it into a GA spec and is unlikely to be used in future versions of the spec. So if someone is using it, I'm hoping this change doesn't break them and just becomes legacy behavior once we release a GA.

**Comment by tianon** [comment]
I don't have much Hub access (nor do I want it, TBH!), but I was able to get a report of popular media types, some of which had pretty low usage, and this one didn't even make the list (as what is IMO a useful data point).

I know at least @rumpl has seen this and might be willing to relay the conversation to the WASM folks who were at least discussing using this (in the doc you linked :grin:).

Maybe we can bring it up in the next call just to make sure we get as many eyes on it as we reasonably can?  Perhaps it's worth making a straw-man PR so we have something more concrete to ~~argue about~~ discuss? :innocent:

**Comment by brackendawson** [comment]
inert
