### ISSUE TITLE
Description in two files for one  component is conflict.

### ISSUE THREAD

**Issue by bettermultiply** [opencontainers/image-spec#1175]
It seems that there is a conflict in the statement regarding the 'image index'.  In `image-spec/image-layout.md`, it says that an image index is optional. But in `image-spec/image-layout.md`, it says that index.json file MUST exist and MUST be an [image index](https://github.com/opencontainers/image-spec/blob/main/image-index.md) JSON object.

**Comment by sudo-bmitch** [comment]
Hi @bettermultiply, I searched image-layout.md and couldn't find the word "optional". Can you clarify where you are seeing that?

**Comment by sudo-bmitch** [comment]
These are referring to two different contexts. In the spec.md, the description is for an "OCI Image" that one could build and later deploy to an OCI runtime. In that situation, the Index is optional, and would typically be seen when people package a multi-platform image. Building a single platform image could be done without an Index.

In the image-layout.md, this description is for a filesystem structure for transporting OCI content. OCI images can be transported other ways, such as with a container registry, described by the distribution-spec. For the OCI Layout, the `index.json` file is required as a listing of multiple OCI images packaged in the directory structure. The individual images packaged in the Layout may, or may not, have their own Index manifest.

An alternate way to think of the Layout is a filesystem equivalent to a repository on a registry. The repository may have multiple tagged and untagged images. And we use the same Index data structure to list those manifests in the Layout. The `index.json` file itself is not part of the OCI image, it's part of the OCI Layout.

**Comment by bettermultiply** [comment]
Oh, I understand, thank you for your patient explanation.

**Comment by ezekg** [comment]
> An alternate way to think of the Layout is a filesystem equivalent to a repository on a registry. The repository may have multiple tagged and untagged images. And we use the same Index data structure to list those manifests in the Layout. The `index.json` file itself is not part of the OCI image, it's part of the OCI Layout.

Chiming in since the topic is about ambiguity i.r.t. `index.json`.

After implementing the OCI spec for a private registry, my thoughts are that `index.json` should really have a media type of `application/vnd.oci.layout.index.v1+json`, not `application/vnd.oci.image.index.v1+json` (note: `oci.layout.index` vs `oci.image.index`). This is because the `index.json` is not actually an index that should be served via `/v2/<name>/manifests/<reference>`, even if at face value all manifests and indexes should be served.

This ambiguity caused some confusion on my end during implementation.

I assumed a request with an `Accept` header of `application/vnd.oci.image.index.v1+json` should get back the best and earliest match, which in my mind was `index.json` — but that was an incorrect assumption. This approach was incompatible with clients like `docker` and `skopeo` implementing the spec, because although `index.json` _is_ an index according to its media type, it's not the same type of index as a nested image index under the layout index's `manifests` property.

This distinction was confusing to me and is why I thought a media type of `application/vnd.oci.layout.index.v1+json` would make it clearer. The `index.json` is related to the layout, not the image, similar to `application/vnd.oci.layout.header.v1+json`.

Maybe I'm off here, but figured I'd share my xp.
