### ISSUE TITLE
[Manifest] Clarification of "old format"

### ISSUE THREAD

**Issue by RobDolinMS** [opencontainers/image-spec#122]
The Backwards Compatibility section has a number of references to "old format."  

It may be helpful to clarify what "old format" is referring to.

**Comment by stevvooe** [comment]
Link?

**Comment by philips** [comment]
@stevvooe In manifest.md. I will submit a PR to fix up.

**Comment by philips** [comment]
FIxed in https://github.com/opencontainers/image-spec/pull/123

**Comment by philips** [comment]
Moving discussion to #123.

**Comment by stevvooe** [comment]
@philips Should we avoid closing these until the PR merges?

**Comment by wking** [comment]
On Tue, Jun 07, 2016 at 03:24:19PM -0700, Stephen Day wrote:
> @philips Should we avoid closing these until the PR merges?

GitHub makes this easy to do [1], and that syntax works in PR topic
messages too.

[1]: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by philips** [comment]
@stevvooe @wking Sure, I can leave these open.

The last few issues by @RobDolinMS have been good questions but trivial to fix. As the issue can't really drive discussion because the fix is non-obvious prose stuff so I just closed them to focus on the actual fix instead. If other @opencontainers/image-spec-maintainers have opinions about how to handle these sorts of things we can discuss here. In the meantime I will just leave the issues open until the PR merges.

Also @wking GitHub keeps threatening to deprecate that feature FWIW IIRC.

**Comment by stevvooe** [comment]
@philips Typically, I'm used to using auto-close, just in case the PR goes sideways. I understand this can split discussion, so either way is fine.

**Comment by vbatts** [comment]
Either way is fine with me. We've had a mix of both.
