### ISSUE TITLE
export types for implementation

### ISSUE THREAD

**Issue by runcom** [opencontainers/image-spec#133]
are types under `image/` exportable for implementation rather than defining our own in pkgs?

**Comment by wking** [comment]
On Mon, Jun 13, 2016 at 03:32:49PM -0700, Antonio Murdaca wrote:
> are types under `image/` exportable for implementation instead of
> defining our own in pkgs?

I'd expect so, but either way it's probably worth documenting.
runtime-spec references its Go types as bindings since
opencontainers/runtime-spec#342, and we may want similar language
here.

**Comment by vbatts** [comment]
I was mulling on this as well.

**Comment by philips** [comment]
@vbatts what is your hesitation?

**Comment by vbatts** [comment]
nothing more than a clean layout of the source. Reference structs in one import path, and validation in another.

**Comment by stevvooe** [comment]
@vbatts @runcom @philips Ultimately, I think this is a good idea. I do share @vbatts hesitation, but would like to see Go implementations using common implementations to avoid fracture.

https://godoc.org/github.com/docker/distribution/manifest is the package structure used in the Docker implementations. There is schema back-registration in https://godoc.org/github.com/docker/distribution#RegisterManifestSchema. Its not perfect, but could inform the implementation and help avoid mistakes.

That said, the biggest problems that arise are dependency coupling. It might be easier to deal with backwards compatibility if the algorithms are exported, rather than the structures themselves.

**Comment by vbatts** [comment]
@runcom do you want to try your hand at this?

**Comment by runcom** [comment]
@vbatts sure, what's in docker/distribution is a nice start as well

**Comment by wking** [comment]
Fixed by #172?

**Comment by philips** [comment]
I think this is fixed by #172 so I am closing it. Let me know if this isn't true @runcom
