### ISSUE TITLE
Clarification re layer parents: can it be omitted? Are non-chains possible?

### ISSUE THREAD

**Issue by kamalmarhubi** [opencontainers/image-spec#37]
Will it be possible with this spec to share tar blobs across multiple images? Requiring a parent field in a layer's metadata could make that impossible, depending on what's hashed and how, but I've had trouble finding out if a parent is required.

My ideal is to be able to specify an image as a collection of tar files that contain disjoint collections of files. Multiple images might share data or libraries, and I'd like to maximize that sharing and minimize the number of distinct tar files that need to be transferred and stored.

I've tried to figure this out from the spec. The schema itself makes no mention of parents. The surrounding markdown files mention parents, as does #25.

**Comment by kamalmarhubi** [comment]
As an aside: I think the choice of the word "layer" is confusing and underdefined in this spec.

**Comment by philips** [comment]
@kamalmarhubi Can you open a new issue on the use of layer and your concerns with it?

**Comment by philips** [comment]
@kamalmarhubi The intention is to allow for images to share blobs. For example you could imagine that the blobs in my example here could be hardlinks to other blobs on the filesystem: https://github.com/opencontainers/image-spec/issues/23#issuecomment-212636147

(similar to like git clone --shared)

Or, you could imagine that a transport over HTTPS could be defined that uses a shared CAS store to serve up requests for multiple images.

**Comment by kamalmarhubi** [comment]
@philips 
> Can you open a new issue on the use of layer and your concerns with it?

I've attempted to do so in #39.

**Comment by kamalmarhubi** [comment]
> Or, you could imagine that a transport over HTTPS could be defined that uses a shared CAS store to serve up requests for multiple images.

Yeah I think this is the ideal I'd like to be easily achievable.

**Comment by timthelion** [comment]
Before we go and invent a new standard for CAS, have the existing, better studied, CAS stores been ruled out? Specifically, IPFS:  [IPFS](https://ipfs.io/) ping @jbenet @whyrusleeping

**Comment by whyrusleeping** [comment]
I would love to chat about this, and i'm sure @jbenet would too

**Comment by timthelion** [comment]
@whyrusleeping Just to let you know, due to my need for de-duplication and fast updates, IPFS support is the No. 1 priority for the [subuser](subuser.org) project. So even if IPFS doesn't get integrated with THIS standard, I'm going to be trying my hardest to get it so that IPFS works with containers in the future :)

**Comment by jbenet** [comment]
@timthelion thanks for the ping! I think we have a lot to contribute here, particularly with a few relevant pieces and tooling from ipfs land. Can we catch up separately first (@timthelion @philips), to make sure we add the most value here and are brought up to speed with what you're thinking? Maybe a hangout fri?

Some relevant things of interest:
- IPLD: merkleized data interchange format. -- https://github.com/ipfs/specs/tree/master/ipld this is almost done. think "merklelinking meets JSON" (it's really [CBOR](http://cbor.io/) not json). Can represent the layers as this.
- file importers: import unix/posix files, construct graphs for dedup + smart indexing. we will be working on ipfs-independent tooling for this, some of which may end up part of `git lfs` too.
- `car` -- this is far from built because we havent needed it, but may be interesting to OCI eventually. https://github.com/ipfs/archive-format

**Comment by wking** [comment]
On Tue, Apr 19, 2016 at 09:39:42PM -0700, Kamal Marhubi wrote:
> Will it be possible with this spec to share tar blobs across
> multiple images?

I think the answer is clearly “yes” from the remainder of discussion
in this issue, the (new since this issue) layer documentation, and the
(new since this issue) image-layout documentation.  While I'm
personally fond of using IPFS to distribute directories [1], that
doesn't seem to have picked up much steam.  And I don't think there's
anything else in this issue that still needs to be addressed.

[1]: https://github.com/opencontainers/image-spec/issues/37#issuecomment-212718381

**Comment by vbatts** [comment]
I'm not sure this issue is still aligned with what finally was released as v1.0.0 (in 2017). 
I read this as a use of the image-index, or potentially a use-case for the discussed references API.

Closing this issue. Please open a new one so we can refine the particular need.
