### ISSUE TITLE
ensure that layer unpacking algorithms are windows compatible

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/image-spec#415]
Recently, there has been a lot of activity in [`layer.md`](https://github.com/opencontainers/image-spec/blob/master/layer.md) around the unpacking procedure. I am not sure if we've fully evaluated this in the context of windows containers and other platforms.

As a strawman, there is a lot of discussion around links. How are these correctly handled in NTFS?

@jstarks @RobDolinMS

**Comment by RobDolinMS** [comment]
Thanks @stevvooe.  I've sent an email ping to @jhowardmsft and @jstarks to encourage them to take a look.

**Comment by philips** [comment]
@RobDolinMS ping.

**Comment by stevvooe** [comment]
@jhowardmsft @jstarks PTAL

**Comment by AkihiroSuda** [comment]
* some notes about sockets, block devices, char devices, and FIFOs seem needed
* It should be clarified that the content of rootfs is extracted under the root of the `%SystemDrive%`?
(Is there any standard about `%SystemDrive%`? Is it guaranteed to be always `C:`?)

**Comment by AkihiroSuda** [comment]
PTAL @jhowardmsft @jstarks

**Comment by vbatts** [comment]
can i test this on a vm? Is windows 7 suitable enough?

**Comment by vbatts** [comment]
like fifos, symlinks, sockets, character devices. These are platform specific.
The assumption on the current doc, that is readying for v1, is that it is unless otherwise specified targeting POSIX. As windows specific changes come in, we'll just denote those platform dependent differences, so that a post-v1 addition will not break the current POSIX expectations.

_(i realize it's not strictly POSIX or the "POSIX is dead" or whatever, but it most closely matches what happens here)_

**Comment by jonboulle** [comment]
POSIX is dead?? no-one told me!!

**Comment by jonboulle** [comment]
(I would also really like to hear more input from our MS friends on how the current layer specification is working out for them)

**Comment by vbatts** [comment]
> POSIX is dead?? no-one told me!!

2016 article that recently floated around
http://www.cs.columbia.edu/~vatlidak/resources/POSIXmagazine.pdf
Take it with a grain of salt ...

**Comment by stevvooe** [comment]
PTAL @RobDolinMS @jstarks @jhowardmsft

**Comment by philips** [comment]
PTAL @RobDolinMS @jstarks @jhowardmsft

**Comment by philips** [comment]
@RobDolinMS @jstarks @jhowardmsft This is a v1.0 blocking issue.

**Comment by RobDolinMS** [comment]
Thanks @Philips.  I've pinged @jstarks @jhowardmsft and a few others from their team with a reminder to look at this issue.

**Comment by vbatts** [comment]
I'm in favor of this being post-v1.0.0, as it has been a topic since Oct 2016 with no semantics for it. If the current semantics for a layer type are found to not be compatible then we'll have to make a new layer type later.

**Comment by philips** [comment]
+1 to moving to post v1.0.0 due to the lack of movement.

**Comment by jstarks** [comment]
Essentially I don't think there are any serious problems, just missing information on Windows specifics. I can take a shot at a PR to include these specifics, but here they are in comment form first:

Windows layers cannot currently have sockets, block devices, character devices, or FIFOs (these concepts don't currently mean anything on Windows).

Windows doesn't look at `uid`, `gid`, or `mode`, since these concepts don't exist in Windows file systems. Instead, Windows relies on the Windows-specific metadata described below.

We don't support `xattrs` either; Windows extended attributes are different enough that they should use a different portion of the tar PAX metadata if we want to support them (currently they are not supported in Docker).

There are a few tar PAX extensions we added to support necessary Windows metadata. Specifically, the Windows file attribute data is stored in `MSWINDOWS.fileattr`. The security descriptor is stored in binary form, base64 encoded, in `MSWINDOWS.rawsd`. If `MSWINDOWS.mountpoint` is present on a symbolic link, then instead of a standard Windows symbolic link, a mount point (directory junction) should be created.

Finally, Windows images should use the `LIBARCHIVE.creationtime` to encode the creation time for files.

**Comment by vbatts** [comment]
@jstarks thank you for this. The implications of this are beyond what can be covered in this spec for the time being, except for just having a comment on only what _is_ capable currently.
I'm going to tag this as post-v1.0.0. Though given what you've said, it would likely be best to open new issues to concisely cover the points that need working toward.

**Comment by vbatts** [comment]
@jstarks is this still needed or can we close it?

**Comment by cyphar** [comment]
> Finally, Windows images should use the LIBARCHIVE.creationtime to encode the creation time for files.

`ctime` is supported by several other PAX extensions, is there a reason to use LIBARCHIVE over the more common ones (SCHILY and GNU)?

**Comment by vbatts** [comment]
This obviously did _not_ block v1.0, and has not been an issue since. I'm guessing WSL solved a number of issues like this 😸
