### ISSUE TITLE
Detail compatibility requirements of v1.0

### ISSUE THREAD

**Issue by kamalmarhubi** [opencontainers/image-spec#42]
I have gathered from various discussions that the intention is to have v1.0 be compatible with Docker's spec. If that's right, the goal should be detailed in the README or elsewhere, along with some justification.

**Comment by kamalmarhubi** [comment]
The scope of "allowed" deviations from this should also be outlined. It's a bit unclear to a newcomer what the scope of this project is, assuming this restriction.

**Comment by kamalmarhubi** [comment]
Copying [@vbatts' response on #39](https://github.com/opencontainers/image-spec/issues/39#issuecomment-213531134):

> @kamalmarhubi It seems odd, granted, and I would like it to not be the case either. The intention of the spec is to carry forward lessons learned, and build on the pervasive industry standards. So some changes that would break much infrastructure need to be planned and coordinated. It's not an entirely clear line.

**Comment by kamalmarhubi** [comment]
Thinking a bit more: Docker has not had an issue introducing an incompatible image format in their v2.x spec. Given that, it's really unclear to me why Docker's image format is so privileged that the OCI image-spec v1.0 can't be incompatible with it.

**Comment by wking** [comment]
On Fri, Apr 22, 2016 at 12:17:07PM -0700, Kamal Marhubi wrote:
> Thinking a bit more: Docker has not had an issue introducing an
> incompatible image format in their v2.x spec.

I expect @stevvooe can answer this, but my guess is that a
consumer-side “has not had an issue” is because the Docker folk did a
lot of legwork on the backend to provide backwards compatibility ;).
The restriction on this repo is probably just “if we break backwards
compatibility and require that backend legwork, we should only do it
for a good reason” [1].  Also relevant to backwards compatibility and
possibly hard to work around is handling crypo/verification [2].

[1]: https://github.com/opencontainers/image-spec/pull/6#issuecomment-207063134
[2]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/2RC_GN35ltU
     Subject: Signature verification after image-format translation
     Date: Fri, 15 Apr 2016 14:50:18 -0700
     Message-ID: <20160415215018.GR23066@odin.tremily.us>

**Comment by philips** [comment]
@kamalmarhubi we should try not to introduce an incompatible serialization/layer mime-type because it will cause lots of duplication on the backend for public registries that are holding onto terabytes of layers and make it so they can't "port" them forward to OCI without creating a copy.

@wking Docker has had to [break old clients in the past](https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/). This is something we need to keep in mind with schema changes; someone pushing and signing schema v2.3 could potentially cause schema v2.2 clients to not work. There are good reasons for doing these sorts of things but ideally we document the path and leave options open for users via signing/pushing multiple mime-types, etc.

**Comment by wking** [comment]
On Thu, Apr 28, 2016 at 04:35:33PM -0700, Brandon Philips wrote:
> … via signing/pushing multiple mime-types, etc.

+1 to being able to simultaneously distribute several serializations
of your container (e.g. pushing older formats, potentially to older
registries for Docker 1.5 and earlier).  I keep calling that the
“registered protocol” approach [1], but am happy to switch terms if
there's already an accepted name.

And with the trusted signer publishing the alternatives, the
translation issue laid out in [1] are easy to solve (just have them
sign everything they push).  It only gets dicey when it's the registry
(without the trusted key) doing the translating.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/2RC_GN35ltU
     Subject: Signature verification after image-format translation
     Date: Fri, 15 Apr 2016 14:50:18 -0700
     Message-ID: <20160415215018.GR23066@odin.tremily.us>

**Comment by stevvooe** [comment]
I'm not sure if I can contribute here other than to say that we broke compatibility for very good reasons. 

The short answer is that we "broke it" for very good reasons and we did so slowly and methodically.  This was nothing but painful for the engineers involved, the fruits of which reflected over a year of work from a talented team of Docker employees, contributors, partners and users. It _was_ a huge issue but what we did has addressed problems with security, opened up multi-architecture support, pushed into content-addressability and will lay the ground work for future improvements. OCI should benefit directly from most, if not all of these changes.

It's also important to note that many of the members of the OCI group took part in the Docker V2 image format specification process. @vbatts introduced the interim manifest format (V2.0) and participated in the manifest list/schema definition. Through GitHub and the Docker Distribution Working Group, we also took feedback from CoreOS, Google, Red Hat, IBM and other partners. The V2.2 manifest list specification, under one form or another, was under public review for nearly 9 months. While OCI Image specification isn't a direct continuance of that group, there is direct lineage and good ideas from that effort that will help to ensure this effort is successful. Dropping those ideas or compatibility out of hand is an simply an unwise proposition.

Should we consider Docker's image format to be privileged with respect to compatibility? Probably not. But, if compatibility is broken, the reasons must be technically sound and ultimately benefit the end user of the software.

**Comment by philips** [comment]
Exactly. Thanks for the detailed reply @stevvooe.

**Comment by kamalmarhubi** [comment]
Thanks @stevvooe, @wking, @philips!

**Comment by philips** [comment]
I am going to close this out and try and write-up the overall sentiment from @stevvooe and my comments into the media-types.md compatibility matrix.

Thanks for the conversation @kamalmarhubi
