### ISSUE TITLE
media types and descriptors, explain more deeply

### ISSUE THREAD

**Issue by philips** [opencontainers/image-spec#493]
During last weeks call we discussed how the basic JSON objects in OCI shouldn't embed their own media types because they are not designed to be discovered or detected. Instead the media type should be declared explicitly in a descriptor and the contents verified via digest before interpretation.

This is a safety mechanism in the system so that people follow a strict flow of logic when interpreting things off the wire. We should make this thinking explicit in the overview of the spec.

cc @stevvooe

**Comment by wking** [comment]
On Tue, Dec 13, 2016 at 11:04:19PM -0800, Brandon Philips wrote:
> During last weeks call we discussed how the basic JSON objects in
> OCI shouldn't embed their own media types…

Isn't this being addressed in #411?

**Comment by stevvooe** [comment]
@philips Was there more we needed here?

**Comment by vbatts** [comment]
@stevvooe are we going to strip/make-OPTIONAL `mediaType` on everything except for descriptor objects?

**Comment by stevvooe** [comment]
> @stevvooe are we going to strip/make-OPTIONAL mediaType on everything except for descriptor objects?

This is the plan. Most are reserved fields.

Did you we need implementation direction for descriptor usage here? I am not sure what is actionable on this issue.

**Comment by vbatts** [comment]
right on.

**Comment by philips** [comment]
@stevvooe I think what needs to happen is an entry in the descriptor spec about how this is the only place mediaType should appear and removal of mediaType from other objects as necessary.

**Comment by wking** [comment]
On Wed, Feb 01, 2017 at 05:21:04AM -0800, Brandon Philips wrote:
> I think what needs to happen is an entry in the descriptor spec
> about how this is the only place mediaType should appear and removal
> of mediaType from other objects as necessary.

Hasn't this already happened between #411 (and the follow-up #531)?
Or are you interested in dropping the reserved-field entries [1,2]?
Or are you interested in dropping the context based,
descriptor-mediaType value restrictions [3]?

I'm fine with dropping the reserved fields.  But I think dropping the
context based value restrictions will make manifest(-lists) much less
reliable, because we'd no longer be recommending the use of OCI types
or requiring implementations to support them.

[1]: https://github.com/opencontainers/image-spec/pull/411#discussion_r91774988
[2]: https://github.com/opencontainers/image-spec/blame/5fccf471dfc2e02d5509daf0feddeab86f80510a/manifest.md#L23
[3]: https://github.com/opencontainers/image-spec/blame/5fccf471dfc2e02d5509daf0feddeab86f80510a/manifest.md#L52

**Comment by stevvooe** [comment]
@wking Yes, that should cover it. Closing this.

@philips If you disagree, feel free to re-open and I'll tackle this directly.
