### ISSUE TITLE
v1.Manifest is no longer compatible with docker

### ISSUE THREAD

**Issue by vishvananda** [opencontainers/image-spec#562]
I think this was intentional, but I wanted to verify since this changed between rc3 and rc4.

Now that v1.Manifest no longer has a self describing MediaType associated with it, it is incompatible with the docker layout for manifest. This means converting back and forth is a bit trickier. Given an oci manifest origManifest, converting it to docker format (so you can upload it into a v2 registry, for example), used to look like:

```go
manifest := origManifest
manifest.mediaType = "application/vnd.docker.distribution.manifest.v2+json"
manifest.Config.MediaType = "application/vnd.docker.container.image.v1+json"
for _, l := range manifest.Layers {
    layer.MediaType =  "application/vnd.docker.image.rootfs.diff.tar.gzip"
}
```

Now it is necessary to wrap the manifest in a new version that has the removed field. For example:

```go
type maybeDockerManifest struct {
    v1.Manifest
    MediaType string `json:"mediaType,omitempty"`
}
manifest := maybeDockerManifest{Manifest: origManifest}
manifest.mediaType = "application/vnd.docker.distribution.manifest.v2+json"
manifest.Config.MediaType = "application/vnd.docker.container.image.v1+json"
for _, l := range manifest.Layers {
    layer.MediaType =  "application/vnd.docker.image.rootfs.diff.tar.gzip"
}
```

This isn't hugely painful, but I wanted to make sure the ramifications of changing that field and breaking compatiblity are understood.

**Comment by vbatts** [comment]
@stevvooe what's your position on the `mediaType` field not being present in this files (being marked as reserved)

**Comment by stevvooe** [comment]
This removal is intentional. The field has only served to cause massive confusion, of which this issue is an example. The format was never meant to be self-describing nor is it so support autodetect. Doing so is both insecure and broken. To understand this, compare the usage of the mediatype field you are pointing out with the descriptor usage around it. It is not supposed to be there.

The main goal we want with compatibility is to remove the need to rewrite layers, which is preserved. The rest of the metadata, manifests and config will undergo a slight change, but that should cause any issues and should largely be transparent.
