### ISSUE TITLE
Reconsider "Sparse files SHOULD NOT be used" restriction?

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/image-spec#733]
https://github.com/opencontainers/image-spec/commit/f5a91ffe001afe2308628b112f3d9534fb94c2da added the following sentence to `layer.md`:

```
[Sparse files](https://en.wikipedia.org/wiki/Sparse_file) SHOULD NOT be used because they lack consistent support across tar implementations.
```

GIven that most implementations use Go and now Go supports sparse files (https://github.com/golang/go/issues/13548), can we reconsider this?

@vbatts @stevvooe

**Comment by wking** [comment]
In #255, @vbatts made this an implementation-support issue instead of a filesystem-support issue, because he [wasn't aware of many filesystems that didn't support sparse files][1].  The recent Go support for sparse files has turned up a number of cases that don't support sparse files (e.g. see golang/go@718d9de60fd4337d9044cdc2c685177dd2177ef6 giving up on trying to parameterize this, with the previous parameterization suggesting FFS and HFS+ lack support, and AUFS has only partial support).  However, if that's the argument we want to make, we'd still want to adjust the spec to mention inconsistent OS/FS support instead of inconsistent tool support.

[1]: https://github.com/opencontainers/image-spec/pull/255#r77822800

**Comment by vbatts** [comment]
I'm still keen to keep that sparse files SHOULD not be used. If an
implementation uses them, they are accepting the risk of checksums not
validating or similar.

**Comment by wking** [comment]
On Thu, Sep 21, 2017 at 11:31:03PM +0000, Vincent Batts wrote:
> If an implementation uses them, they are accepting the risk of
> checksums not validating or similar.

That's only a problem for unpack/repack, though right?  That seems
like less of a “passing image data between parties” issue and more of
a “some consumers may create sub-optimal images if they use an image
containing sparse files as a base” issue.  It's a risk, and I'm fine
calling it out (which we don't do at the moment), but I'm not sure
it's a SHOULD-worthy risk.  Folks will still be able to unpack the
image (assuming their local OS/FS is capable of supporting sparse
files or they have a big enough disk to hold the unsparsed file) and
run containers from it, which seems like the primary use-case
image-spec is enabling.  And if folks occasionally pack a new image
based on the content and happen to not recycle the same tar blob, it
still seems like a CAS win to not be holding unsparsed copies.

**Comment by stevvooe** [comment]
In general, sparse files should not be used. You're still welcome to use them but I don't see the benefit, especially with compression.

@AkihiroSuda Is there are particular use case that you had in mind?

**Comment by AkihiroSuda** [comment]
- adduser (with large uid value), which seeks /var/log/lastlog depending on uid value: https://github.com/moby/moby/issues/5419

**Comment by stevvooe** [comment]
@AkihiroSuda What if we added a section that says implementations should be able to consume them?

Considering the sparse support of sparse files, I'm a little reticent to remove this from the specification. It doesn't say you can't use them, but generating them may come with consequences.

**Comment by AkihiroSuda** [comment]
OK, closing this issue.

However, if we encounter real compatibility problem across different implementations, I'd like to reopen this issue with some new annotation convention (`org.opencontainers.image.has-sparse-tar-layer-blah-blah-blah`)

**Comment by vbatts** [comment]
Understandable
