### ISSUE TITLE
Should include an image genesis label?

### ISSUE THREAD

**Issue by kbaegis** [opencontainers/image-spec#746]
As I think about this, I was considering adding a new label that would be great to see on images globally. Every time FROM is called, I would like to append to a genesis value. 
For example:
FROM alpine:latest
...
COMMIT alpine.altered:latest
FROM alpine.altered:latest
...
COMMIT alpine-with-netconf:latest

ENV image-genesis="alpine:latest;alpine.altered:latest;alpine-with-netconf:latest"

May or may not be useful for this standard, but I thought I'd chime in.

**Comment by cyphar** [comment]
This is out of spec, since image builds are not part of `image-spec` (in fact one of the more commonly used image builders, `umoci` doesn't really have any sort of Dockerfile syntax). Not to mention that you could easily modify the image to change the history.

If you're looking for a way of having a chain of trust of images as they're passed around, I'd recommend looking at some image signing tools or something similar.

**Comment by kbaegis** [comment]
Sorry, I think I had intended for this to go here: http://label-schema.org/rc1/

OT. Thanks :)
