### ISSUE TITLE
base image label

### ISSUE THREAD

**Issue by MarcoSchaar** [opencontainers/image-spec#783]
Hi
small question to annotations.
We would like to add labels like
org.opencontainer.[image].base_image
org.opencontainer.[image].base_image_tag

is it free choice or are there rules to follow?

**Comment by vbatts** [comment]
Hey there, two things:
* Annotation keys are effectively free text, so you _could_ use these in your images, but since your examples are using the OCI official prefix, if this full key ever got official utilized then it could collide with how you are using it
* Perhaps safer to use your own prefix of annotation to store this information
