### ISSUE TITLE
Nullability of optional fields in manifests and descriptors

### ISSUE THREAD

**Issue by tofay** [opencontainers/image-spec#894]
It's not clear whether optional fields in manifests and descriptors can be null. By extension, it's also not clear whether or not the canonicalized form of a manifest should omit or set to null any optional fields that are not provided.

I noticed that the config spec and schema allows that optional fields may be null: https://github.com/opencontainers/image-spec/blob/8b9d41f48198a7d6d0a5c1a12dc2d1f7f47fc97f/config.md?plain=1#L93

The schemas for manifests and descriptors don't allow for null values. Should the spec be updated to clarify this? Happy to do that.

**Comment by sudo-bmitch** [comment]
From the Go implementations, the preference is to omit the field, rather than explicitly set it to null, in the JSON. That's seen with [omitempty](https://github.com/opencontainers/image-spec/blob/6ad7100eb087e43398e9ea8fe44fffc1501b8984/specs-go/v1/descriptor.go) defined on various fields. I don't believe this is a hard requirement, but it's a convention you'll see from most implementations.

**Comment by sudo-bmitch** [comment]
It looks like the associated issue was resolved. If more is needed here, let us know and we can reopen.
