### ISSUE TITLE
About the necessity to support reference for image index

### ISSUE THREAD

**Issue by imeoer** [opencontainers/image-spec#971]
The reference type (`subject` field) has been released to `v1.1.0-rc2`, thanks to the working group, it's an excellent feature. The image distribution like Harbor is able to use `subject` to do garbage collection of associated artifacts/images and present the association between artifacts/images in the UI interface.

But we noticed that only image manifest and artifact manifest support this field, my question is do we need to support reference for image index as well?

If it is supported, we could use it in some possible scenarios like the below:

- [Cosign](https://github.com/sigstore/cosign) supports signing the entire manifest list for the related image.
- [Accled](https://github.com/goharbor/acceleration-service) supports converting all images in the OCIv1 manifest index to [Nydus](https://github.com/dragonflyoss/image-service) or [eStargz](https://github.com/containerd/stargz-snapshotter) formats and generate new manifest indexes.

Does this consider ambiguity if the index supports the `subject` field? For example, only some of the manifest in the index are actually related to each other, and the various artifact/manifest generation tools may not clearly promise this.

**Comment by sudo-bmitch** [comment]
In the examples given, is the index the manifest with the subject, or is the index the manifest that the subject references? In other words, a cosign signature is an artifact with a subject that can point to a multi platform image. We don't need the subject on the index for that.

**Comment by imeoer** [comment]
@sudo-bmitch Thanks for the reply, indeed the cosign signature can totally use artifact with a subject. What do you think the accelerated image (with multi platform) can point to an original multi platform image? It seems a little strange if image conversion tools only handle part of manifests in the index.

**Comment by sudo-bmitch** [comment]
@imeoer 

Why not replace the existing image tag with the accelerated image? Is there a reason to ship both in the same repo and use the subject to link them, rather than having a single image? The Index spec specifies that multiple entries for the same platform should use the first matching entry unless the runtime has a reason to pick one of the later entry, which means everything could be placed in the same Index.

If this spans to another repository, the subject won't go across repositories, it's for a digest in the same repo.

If you want a way to denote the original source in the accelerated image, then an annotation may be a better method.

The hesitation to add a subject to the Index is because it creates logical loops in the DAG. You can create manifest B, and then create Index A with both a child manifest and subject manifest set to the digest of B. Then any processes that recursively check for referrers to process the image (GC, copying, exporting, UIs, etc) would list children of A, open B, list the referrers of B, return to A, and repeat indefinitely.

**Comment by imeoer** [comment]
@sudo-bmitch 

> Why not replace the existing image tag with the accelerated image? Is there a reason to ship both in the same repo and use the subject to link them, rather than having a single image? The Index spec specifies that multiple entries for the same platform should use the first matching entry unless the runtime has a reason to pick one of the later entry, which means everything could be placed in the same Index.

Some scenarios may consider the image tag to be immutable, rewriting the tag may result in behavior that is not expected by the user, and if accelerated images are placed in the manifest index, we need to support the runtime (enhance default [platform matcher](https://github.com/containerd/containerd/blob/main/platforms/platforms.go#L126) implementation for various acceleration image format) to help the user choose whether to pull the original image or the accelerated image.

> The hesitation to add a subject to the Index is because it creates logical loops in the DAG. You can create manifest B, and then create Index A with both a child manifest and subject manifest set to the digest of B. Then any processes that recursively check for referrers to process the image (GC, copying, exporting, UIs, etc) would list children of A, open B, list the referrers of B, return to A, and repeat indefinitely.

This is reasonable and makes sense, thanks for the detailed explanation.

**Comment by sudo-bmitch** [comment]
> Some scenarios may consider the image tag to be immutable, rewriting the tag may result in behavior that is not expected by the user

I'm definitely one of those people, especially when I'm the user of the image. But the producer of the image can do this before it's published to the world (build on a private registry, or use an OCI Layout). Another option is to pick a tag scene (`v1.0.0-accel`).

**Comment by imeoer** [comment]
Thanks for all your patient replies! cc @sudo-bmitch
